# Replica of the scITD Analysis

The goal of this ntoebook is to replicate, on the breast-cancer data which is provided, the analysis which scITD conducts in order to gain insight on how tensor decompositions can be used to meaningfully analyse cell-cycle data.

## 0. Imports:

In [151]:
import numpy as np
import pandas as pd
import scanpy as sc

import tensorly as tl
from tensorly.decomposition import tucker

## 1. Data import:

In [137]:
adata = sc.read_h5ad("data/breast_cancer_zikry_wayne/44PE_merged.h5ad")

Understanding our data:

In [138]:
print(f'n_obs x n_vars: {adata.shape}')

n_obs x n_vars: (90594, 103)

In [139]:
print(f'cell barcodes (row index): {adata.obs_names}\n')
print(f'gene/feature names (column index): {adata.var_names}\n')

cell barcodes (row index): Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '6178-6', '6179-6', '6180-6', '6181-6', '6182-6', '6183-6', '6184-6',
       '6185-6', '6186-6', '6187-6'],
      dtype='object', length=90594)

gene/feature names (column index): Index(['cyto_mean_ERa', 'cyto_mean_Ki67', 'cyto_mean_PR', 'cyto_mean_DAPI',
       'cyto_mean_HES1', 'cyto_mean_p38', 'cyto_mean_p16', 'cyto_mean_PH3',
       'cyto_mean_p65', 'cyto_mean_pAKT',
       ...
       'nuclear_mean_bCat', 'nuclear_mean_SKP2', 'nuclear_mean_E2F1',
       'nuclear_mean_HER2', 'nuclear_mean_YAP1', 'nuclear_mean_CDT1',
       'nuclear_mean_pCdc6', 'nuclear_mean_cycE2', 'DNA_int', 'pRB/RB'],
      dtype='object', length=103)

In [140]:
adata.obs

,core,binucleated,CellID,GMM_phase_labels,DNA_int_obs,nuclear_mean_cycA2_obs,Endocycle,drug_name
0,1.0,0,0,G0,2.482551,585.705651,Diploid,Control
1,1.0,0,1,S,2.267976,371.223898,Diploid,Control
2,1.0,0,2,S,2.783111,1585.394977,Diploid,Control
3,1.0,0,3,G0,2.195485,111.103687,Diploid,Control
4,1.0,0,4,G1,2.199392,131.529825,Diploid,Control
...,...,...,...,...,...,...,...,...
6183-6,8.0,0,6183,S,2.211465,1546.934177,Diploid,Dinaciclib
6184-6,8.0,0,6184,G1,1.799833,147.419776,Diploid,Dinaciclib
6185-6,8.0,0,6185,G1,1.930990,148.797964,Diploid,Dinaciclib
6186-6,8.0,0,6186,G1,4.087362,114.891078,Polyploid,Dinaciclib
6187-6,8.0,0,6187,G0,1.660539,128.065032,Diploid,Dinaciclib

In [141]:
adata.obs['drug_name'].value_counts()

drug_name
RO-3306         22592
Palbociclib     17570
Talazoparib     14458
PF-3600          9202
CVT-313          7385
Control          7110
Dinaciclib       6188
Samuraciclib     6089
Name: count, dtype: int64

In [142]:
pd.DataFrame(adata.X, columns=adata.var_names, index=adata.obs_names)

,cyto_mean_ERa,cyto_mean_Ki67,cyto_mean_PR,cyto_mean_DAPI,cyto_mean_HES1,cyto_mean_p38,cyto_mean_p16,cyto_mean_PH3,cyto_mean_p65,cyto_mean_pAKT,...,nuclear_mean_bCat,nuclear_mean_SKP2,nuclear_mean_E2F1,nuclear_mean_HER2,nuclear_mean_YAP1,nuclear_mean_CDT1,nuclear_mean_pCdc6,nuclear_mean_cycE2,DNA_int,pRB/RB
0,33.236253,329.340122,164.185336,918.853360,110.411405,321.480652,454.437882,236.920570,281.370672,114.953157,...,232.508634,447.116954,142.361852,116.832025,163.726845,157.045526,2498.128728,1102.920722,2.482551,1.615529
1,213.103477,611.276490,1174.773179,460.025662,260.144040,1212.525662,440.814570,280.472682,253.663079,126.983444,...,486.495360,582.495360,167.380510,122.864269,286.300464,248.694896,3870.610209,2393.815545,2.267976,2.126723
2,188.183391,1297.884083,1215.052768,449.261246,246.387543,1336.935986,389.608131,321.261246,257.562284,131.964533,...,412.441781,1847.090183,170.787671,119.810502,281.863014,222.504566,3654.180365,2147.679224,2.783111,2.187872
3,370.501193,175.214399,1291.324582,415.553302,367.265712,1140.675418,540.842880,307.439539,278.285998,124.886635,...,514.115207,195.294931,178.384793,124.158986,291.124424,174.017281,4895.017281,2143.607143,2.195485,0.881578
4,76.006030,1751.752186,646.121495,255.706663,170.353633,1004.617124,309.799518,212.107627,228.789267,137.582153,...,310.319298,671.204094,137.091813,106.673099,172.815205,967.381287,3436.363743,1264.115789,2.199392,3.259080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6183-6,111.520810,998.093738,848.471691,274.190851,382.217473,1007.234346,508.085114,236.176978,246.051744,119.383577,...,364.302954,1056.803376,166.851477,111.979747,246.891139,195.589873,4277.421941,2075.454852,2.211465,3.205214
6184-6,98.404021,131.331589,532.146792,242.550812,178.311760,924.379785,270.480033,156.541724,192.607546,125.030019,...,312.280784,192.758396,140.451493,89.822761,192.987873,163.861007,2315.606343,1375.266791,1.799833,1.754812
6185-6,112.893740,166.720758,638.205107,252.177100,263.186985,854.596376,215.831137,181.151565,209.538715,111.624382,...,354.228661,374.604542,169.733751,103.410337,254.008614,961.241973,4045.628818,1875.848865,1.930990,3.141703
6186-6,69.801454,132.801246,568.855452,186.567186,290.068951,764.282035,196.247975,178.782555,212.201661,113.844444,...,248.651217,216.647740,148.087679,107.511008,2216.246041,507.805330,2431.222866,1393.193511,4.087362,2.432299
6187-6,94.741059,147.596286,932.502751,362.338377,547.001376,955.493122,594.224553,230.480399,325.117263,123.989684,...,479.959488,168.095949,166.843284,115.971215,280.862473,198.134328,3748.618337,2119.915778,1.660539,1.116007

## 2. scITD-esque analysis:

### 2.1 Pseudobulking:
Our idea is to, for a first go, model our tensor via: $\textit{drug name} \times \textit{proteins} \times \textit{GMM phase}$. We thus aggregate $\texttt{adata.X}$ by $\textit{drug name} \times \textit{GMM phase}$. This will yield a data frame with dimensionality: $\lvert \{ \textit{drug name} \} \rvert \cdot \lvert \{ \textit{GMM phase} \} \rvert \times \lvert \{ \textit{proteins} \} \rvert = 40 \times 103$.

Rewording Mitchel et al. (2024): When $C$ cell-stages from $n$ drug types are collapsed into pseudobulk profiles, the dataset can be represented as a threedimensional matrix: a tensor $T$ with dimensions $n × P × C$, where $P$ is the number of proteins. In our case $C = 5$, $n = 8$, and $P = 103$.

In [143]:
# see form_tensor.R (205-245)
def get_pseudobulk(adata):
    df = adata.to_df()
    df['drug_name'] = adata.obs['drug_name'].values
    df['phase'] = adata.obs['GMM_phase_labels'].values
    return df.groupby(['phase', 'drug_name'], observed=True).mean()

In [144]:
pseudobulk_df = get_pseudobulk(adata)
pseudobulk_df

                    cyto_mean_ERa  cyto_mean_Ki67  cyto_mean_PR  \
phase drug_name
G0    CVT-313          144.403375      650.511004   1046.049668
      Control          172.451072      455.401369   1063.037644
      Dinaciclib        90.205817      268.852801    671.930215
      PF-3600          174.445961      208.426434   1326.868225
      Palbociclib      154.994526      634.704098   1097.190539
      RO-3306          154.467887      819.984471    952.930116
      Samuraciclib     158.189431      152.268561    857.346355
      Talazoparib      168.460938      715.535168   1126.953571
G1    CVT-313          174.206221      750.615114   1100.399208
      Control          172.313717      885.251222   1075.313257
      Dinaciclib       114.639855      425.161080    742.589387
      PF-3600          198.539584      240.081171   1445.282922
      Palbociclib      190.937620      583.075526   1171.386528
      RO-3306          221.184972      996.427606   1060.656297
      Samuraciclib     163.072132      193.862716    931.600047
      Talazoparib      242.090615      566.512759   1307.685062
G2    CVT-313          158.721790     2359.651114   1186.887234
      Control          144.264792     2390.977230   1162.367809
      Dinaciclib       105.028309     1444.125692    807.450749
      PF-3600          176.197554     2265.711638   1535.851249
      Palbociclib      166.421940     2281.990278   1270.865112
      RO-3306          187.539553     3062.533142   1142.612376
      Samuraciclib     114.005606     1181.435188    960.247727
      Talazoparib      169.255457     2355.713045   1264.953912
M     CVT-313          228.192392     3981.239329   1422.028830
      Control          215.970166     4419.456473   1400.172644
      Dinaciclib       159.181807     2320.132360    922.613648
      PF-3600          273.307052     2575.646847   1920.634993
      Palbociclib      309.354928     4008.331305   1555.327332
      RO-3306          380.719360     4452.042030   1451.544029
      Samuraciclib     179.354426     2276.178585   1177.066308
      Talazoparib      262.842580     4031.383641   1623.338601
S     CVT-313          150.435119     1410.625871   1133.801547
      Control          145.254306     1487.983851   1010.050238
      Dinaciclib        99.595067      866.599486    785.470630
      PF-3600          155.962367     1275.603851   1385.180462
      Palbociclib      157.341142     1353.448250   1178.212832
      RO-3306          171.070500     1534.778796   1011.343726
      Samuraciclib     116.360794      794.136991    905.957232
      Talazoparib      174.419240     2519.956482   1256.313091

                    cyto_mean_DAPI  cyto_mean_HES1  cyto_mean_p38  \
phase drug_name
G0    CVT-313           408.072220      258.124475    1192.351613
      Control           416.187741      261.272853    1168.110701
      Dinaciclib        283.607087      249.830882     840.668614
      PF-3600           355.898766      310.288988    1633.678264
      Palbociclib       492.411975      226.868631    1602.962035
      RO-3306           451.569048      223.825998    1169.420685
      Samuraciclib      272.967585      305.267242    1462.874836
      Talazoparib       419.409333      250.409155    1248.542469
G1    CVT-313           415.491355      259.243086    1318.937715
      Control           383.017906      259.032814    1219.184502
      Dinaciclib        282.697839      243.332474     971.906959
      PF-3600           332.249983      312.795122    1842.600718
      Palbociclib       421.256313      230.341434    1705.480797
      RO-3306           485.867506      230.297833    1340.715380
      Samuraciclib      274.823959      310.097282    1627.940894
      Talazoparib       427.598955      261.249881    1463.534732
G2    CVT-313           458.783370      272.521598    1362.429216
      Control           435.443138      270.787634    1235.550684
      Dinaciclib        312.440964      253.251886    1015.964746
      PF-3600           352.938925      311.272044    1873.679764
      Palbociclib       465.162277      245.549296    1804.260189
      RO-3306           552.275681      240.370567    1379.956215
      Samuraciclib      276.881365      292.174715    1615.796365
      Talazoparib       391.805975      257.513424    1393.265739
M     CVT-313           481.182733      319.288385    1618.415045
      Control           463.135879      327.314862    1543.347769
      Dinaciclib        351.036352      250.958270    1168.603725
      PF-3600           398.733118      357.061399    2368.116621
      Palbociclib       499.583684      325.773359    1909.502653
      RO-3306           591.367100      310.705774    1595.840778
      Samuraciclib      318.921079      337.711727    2040.551090
      Talazoparib       479.769225      363.342150    1695.389268
S     CVT-313           420.007960      263.977576    1339.292381
      Control           374.340902      247.955003    1156.471836
      Dinaciclib        294.030934      252.478133     998.254403
      PF-3600           317.613010      283.420705    1755.668085
      Palbociclib       419.368364      231.704372    1694.132410
      RO-3306           449.215766      220.252219    1264.157276
      Samuraciclib      260.019174      289.330654    1556.627115
      Talazoparib       431.483439      258.611611    1429.205682

                    cyto_mean_p16  cyto_mean_PH3  cyto_mean_p65  \
phase drug_name
G0    CVT-313          438.448419     282.967996     235.639437
      Control          430.023437     333.593578     270.472129
      Dinaciclib       366.510921     199.261213     216.779459
      PF-3600          605.818689     305.818700     297.882597
      Palbociclib      547.299325     277.356447     301.143214
      RO-3306          517.950711     331.116988     272.547186
      Samuraciclib     478.325151     237.076561     333.922613
      Talazoparib      621.258235     295.147959     260.007846
G1    CVT-313          453.853468     279.907049     239.919137
      Control          443.275408     288.224448     274.252270
      Dinaciclib       353.772310     201.614201     245.974253
      PF-3600          649.516015     307.267602     292.477587
      Palbociclib      514.246731     276.529393     306.352124
      RO-3306          567.530851     327.339082     284.799598
      Samuraciclib     494.652011     240.542066     308.052741
      Talazoparib      692.604506     316.715154     288.736501
G2    CVT-313          460.031596     361.886138     256.377322
      Control          442.228861     399.648736     293.511323
      Dinaciclib       375.744983     239.060864     238.348577
      PF-3600          692.687057     350.444319     299.479763
      Palbociclib      518.719680     352.351721     322.017343
      RO-3306          614.165738     440.282730     312.847223
      Samuraciclib     477.619869     286.821528     419.705609
      Talazoparib      636.399122     379.701039     279.649275
M     CVT-313          750.380999    5998.899580     275.639687
      Control          865.864314   13678.479838     323.744201
      Dinaciclib       647.412538    5013.909437     246.001917
      PF-3600         1444.433731    4168.836503     431.218454
      Palbociclib      976.243079   12545.681712     355.331849
      RO-3306         1049.694719   16180.439741     333.945747
      Samuraciclib    1018.541186    4915.500890     325.274558
      Talazoparib     1221.046699   15049.859837     302.446555
S     CVT-313          457.787013     319.680486     243.722582
      Control          430.243224     314.079189     262.832093
      Dinaciclib       360.339577     221.031976     238.300931
      PF-3600          623.554090     314.792006     284.974886
      Palbociclib      508.309487     303.713802     309.244334
      RO-3306          527.217381     343.955770     278.128554
      Samuraciclib     457.713997     246.116388     294.720156
      Talazoparib      630.038584     355.483822     277.396784

                    cyto_mean_pAKT  ...  nuclear_mean_bCat  nuclear_mean_SKP2  \
phase drug_name                     ...
G0    CVT-313           159.130375  ...         373.897422         310.917719
      Control           136.940781  ...         415.596918         242.165915
      Dinaciclib        135.456439  ...         359.683842         202.944335
      PF-3600           167.259935  ...         513.547975         340.615423
      Palbociclib       166.415068  ...         383.379074         345.366843
      RO-3306           250.368554  ...         385.748136         258.050502
      Samuraciclib      167.063727  ...         441.793257         277.024667
      Talazoparib       159.299700  ...         440.097317         305.643028
G1    CVT-313           152.841697  ...         384.686015         398.431051
      Control           153.170987  ...         427.418015         360.030457
      Dinaciclib        150.515836  ...         363.537991         442.907607
      PF-3600           169.941715  ...         492.495123         475.199449
      Palbociclib       164.349159  ...         406.204948         408.872357
      RO-3306           221.837129  ...         403.842836         417.731791
      Samuraciclib      172.880105  ...         446.779383         497.542642
      Talazoparib       157.567409  ...         481.220781         447.070557
G2    CVT-313           174.267844  ...         401.698384        1232.579564
      Control           159.121879  ...         436.021799        1140.647331
      Dinaciclib        157.306307  ...         403.301688        1123.172953
      PF-3600           176.709715  ...         546.625385        2545.556993
      Palbociclib       178.464858  ...         422.841605        1455.669664
      RO-3306           267.185417  ...         428.030061        1292.932120
      Samuraciclib      172.578219  ...         501.651472        1447.259730
      Talazoparib       176.634890  ...         482.529876        1291.561547
M     CVT-313           180.452806  ...         473.000492        1143.537582
      Control           203.725267  ...         514.109409         827.858063
      Dinaciclib        138.413349  ...         420.435757         800.931254
      PF-3600           176.837940  ...         597.908546        1349.685805
      Palbociclib       189.935350  ...         515.511790        1225.343583
      RO-3306           314.204986  ...         486.953745         882.511242
      Samuraciclib      210.611290  ...         574.836105         957.423955
      Talazoparib       208.767445  ...         650.138711         602.373411
S     CVT-313           151.097160  ...         382.135283        1130.031331
      Control           140.794021  ...         400.965366         904.016089
      Dinaciclib        146.344029  ...         375.424392        1067.571658
      PF-3600           175.190656  ...         493.425696        1972.849368
      Palbociclib       165.937433  ...         400.239850        1313.580481
      RO-3306           189.448602  ...         384.432889        1192.999150
      Samuraciclib      176.393484  ...         492.779526        1414.882779
      Talazoparib       183.853820  ...         448.884208        1544.271859

                    nuclear_mean_E2F1  nuclear_mean_HER2  nuclear_mean_YAP1  \
phase drug_name
G0    CVT-313              167.022218         104.766739         267.656920
      Control              172.262689         146.320178         274.541835
      Dinaciclib           232.124013         111.047256         322.266315
      PF-3600              193.469573         134.722052         439.363394
      Palbociclib          256.271528         118.686904         338.530922
      RO-3306              172.078472         116.881501         303.693480
      Samuraciclib         232.173223         167.985939         363.745361
      Talazoparib          225.325152         166.093203         348.128651
G1    CVT-313              167.043384         109.518162         276.662237
      Control              172.410726         135.568657         293.351060
      Dinaciclib           225.083509         132.256300         341.001165
      PF-3600              259.448616         153.444715         402.887383
      Palbociclib          186.067318         132.865471         363.470847
      RO-3306              188.819581         130.358985         278.587500
      Samuraciclib         217.043881         169.619419         430.500920
      Talazoparib          224.689738         170.967558         312.220837
G2    CVT-313              170.339305         105.396815         284.143860
      Control              279.673025         139.149489         308.235715
      Dinaciclib           259.413216         156.030937         329.423356
      PF-3600              245.797342         205.733804         441.202463
      Palbociclib          197.124020         109.810902         354.787798
      RO-3306              211.728299         130.456473         276.027082
      Samuraciclib         242.456449         165.636042         415.734265
      Talazoparib          204.471352         155.061530         355.733892
M     CVT-313              180.115504         107.897997         428.093256
      Control              179.399115         118.548167         254.246933
      Dinaciclib           170.894802          97.529734         444.527298
      PF-3600              223.252449         145.424668         366.975755
      Palbociclib          413.398060         191.166063         436.850852
      RO-3306              222.473320         159.323057         300.501084
      Samuraciclib         193.650910         105.572366         287.537823
      Talazoparib          203.134998         117.452470         347.812971
S     CVT-313              179.848632         105.094263         322.754526
      Control              192.540267         116.430539         360.082610
      Dinaciclib           178.043519         145.916375         321.642224
      PF-3600              198.181885         155.105883         346.981766
      Palbociclib          212.996647         132.290378         401.138597
      RO-3306              205.064534         129.859761         261.161381
      Samuraciclib         208.831713         158.526423         355.153045
      Talazoparib          212.071986         177.937368         319.452310

                    nuclear_mean_CDT1  nuclear_mean_pCdc6  nuclear_mean_cycE2  \
phase drug_name
G0    CVT-313              303.890750         3950.125663         1622.876542
      Control              288.284103         4290.762944         1781.923161
      Dinaciclib           498.300064         3155.892429         1521.856980
      PF-3600              414.272472         4628.657355         1973.582249
      Palbociclib          403.906233         4277.173712         1967.538734
      RO-3306              392.626973         3459.839483         1638.153281
      Samuraciclib         355.364020         4308.210978         1840.149694
      Talazoparib          364.012492         4036.838585         1664.216027
G1    CVT-313              854.067025         4235.577983         1758.904036
      Control              922.980997         4558.221008         1870.842548
      Dinaciclib           734.064907         3398.548653         1586.098322
      PF-3600              913.024205         5177.212823         2301.188557
      Palbociclib          875.400786         4855.594911         2154.234434
      RO-3306             1181.801120         3991.263265         1825.527250
      Samuraciclib         892.629535         4573.758532         2062.789292
      Talazoparib          983.269308         4754.240297         1992.187585
G2    CVT-313              252.810312         4855.166055         1719.997815
      Control              375.659309         5191.310374         1870.211228
      Dinaciclib           327.846234         4077.790411         1682.151361
      PF-3600              570.271030         6039.362820         2614.473129
      Palbociclib          268.899738         5529.141099         2162.012849
      RO-3306              336.222622         4697.094879         1874.733266
      Samuraciclib         357.546987         5011.000319         2212.181132
      Talazoparib          392.523205         6128.166165         1870.999038
M     CVT-313              551.045091         8575.948098         1784.949394
      Control              355.771700        11201.685280         1639.122451
      Dinaciclib           348.968053         8311.028100         1642.962978
      PF-3600              520.256927         8652.146380         2646.256915
      Palbociclib          361.473569        13072.265829         1973.040656
      RO-3306              457.094378         9327.993562         1640.522063
      Samuraciclib         281.603586        10894.655949         2117.686029
      Talazoparib          819.695574        19289.176682         1562.247434
S     CVT-313              233.051743         4344.142796         1962.144638
      Control              440.617762         4372.752272         1916.034577
      Dinaciclib           245.051797         3560.298722         1842.794298
      PF-3600              365.398577         4997.176124         2844.047250
      Palbociclib          286.845531         4938.736456         2373.850812
      RO-3306              305.213511         3882.208609         2001.213842
      Samuraciclib         334.031874         4369.506830         2289.047322
      Talazoparib          373.203714         4759.178084         2046.609175

                     DNA_int         pRB/RB
phase drug_name
G0    CVT-313       2.311815       1.091272
      Control       2.288030       1.452735
      Dinaciclib    2.509624       1.176028
      PF-3600       2.864216       2.048346
      Palbociclib   2.319388       1.247827
      RO-3306       2.543820  146319.877856
      Samuraciclib  3.137321       1.921852
      Talazoparib   3.203947       1.285631
G1    CVT-313       2.301897       2.888410
      Control       2.289829       3.201622
      Dinaciclib    2.281020  255306.627628
      PF-3600       2.848082       2.473519
      Palbociclib   2.216782       2.828298
      RO-3306       2.626875       3.640546
      Samuraciclib  2.871864       2.844568
      Talazoparib   3.354347       3.145859
G2    CVT-313       4.322685       3.011587
      Control       4.202613       3.154016
      Dinaciclib    4.374113       3.327159
      PF-3600       4.957050       3.261882
      Palbociclib   4.124663       3.244884
      RO-3306       4.613697       4.249153
      Samuraciclib  4.705511       2.954528
      Talazoparib   4.423095       3.900933
M     CVT-313       4.068831       3.044005
      Control       4.044058       3.059012
      Dinaciclib    4.144042       3.271507
      PF-3600       3.684520       2.843451
      Palbociclib   3.746784       2.924283
      RO-3306       4.049189       3.547855
      Samuraciclib  4.211065       2.913643
      Talazoparib   4.035919       3.261708
S     CVT-313       3.122465       2.957088
      Control       2.881462       3.076139
      Dinaciclib    3.210096       3.204524
      PF-3600       3.697619       3.131417
      Palbociclib   3.070843       3.191199
      RO-3306       3.057785  129079.179284
      Samuraciclib  3.357877       2.898377
      Talazoparib   4.312974       3.863735

[40 rows x 103 columns]

Restating Mitchel et al. (2024): we scale and center in each cell phase across drugs.

In [145]:
def normalize_and_scale(pseudobulk_df):
    return pseudobulk_df.groupby('phase', observed=True).transform(lambda x: (x - x.mean()) / x.std())

In [146]:
pseudobulk_norm_df = normalize_and_scale(pseudobulk_df)
pseudobulk_norm_df

                    cyto_mean_ERa  cyto_mean_Ki67  cyto_mean_PR  \
phase drug_name
G0    CVT-313           -0.288307        0.640205      0.144933
      Control            0.748538       -0.129418      0.232053
      Dinaciclib        -2.291839       -0.865271     -1.773666
      PF-3600            0.822283       -1.103627      1.585057
      Palbociclib        0.103218        0.577854      0.407199
      RO-3306            0.083750        1.308705     -0.332613
      Samuraciclib       0.221325       -1.325146     -0.822796
      Talazoparib        0.601034        0.896698      0.559833
G1    CVT-313           -0.269027        0.590004     -0.018385
      Control           -0.317903        1.055927     -0.134709
      Dinaciclib        -1.807393       -0.536263     -1.677547
      PF-3600            0.359409       -1.176752      1.580839
      Palbociclib        0.163080        0.010216      0.310783
      RO-3306            0.944250        1.440664     -0.202673
      Samuraciclib      -0.556577       -1.336695     -0.801106
      Talazoparib        1.484161       -0.047101      0.942798
G2    CVT-313            0.204596        0.324893      0.094413
      Control           -0.284917        0.377933     -0.018607
      Dinaciclib        -1.613462       -1.225250     -1.654561
      PF-3600            0.796324        0.165837      1.702927
      Palbociclib        0.465322        0.193399      0.481500
      RO-3306            1.180364        1.514993     -0.109667
      Samuraciclib      -1.309492       -1.670030     -0.950259
      Talazoparib        0.561265        0.318225      0.454253
M     CVT-313           -0.318844        0.500060     -0.040644
      Control           -0.488848        0.963164     -0.114291
      Dinaciclib        -1.278740       -1.255381     -1.723477
      PF-3600            0.308673       -0.985356      1.639463
      Palbociclib        0.810077        0.528691      0.408519
      RO-3306            1.802713        0.997600      0.058811
      Samuraciclib      -0.998151       -1.301831     -0.866071
      Talazoparib        0.163119        0.553052      0.637691
S     CVT-313            0.159137        0.009919      0.260428
      Control           -0.040475        0.156512     -0.377625
      Dinaciclib        -1.799681       -1.021008     -1.535542
      PF-3600            0.372096       -0.245947      1.556519
      Palbociclib        0.425219       -0.098433      0.489409
      RO-3306            0.954198        0.245188     -0.370956
      Samuraciclib      -1.153714       -1.158324     -0.914321
      Talazoparib        1.083221        2.112093      0.892088

                    cyto_mean_DAPI  cyto_mean_HES1  cyto_mean_p38  \
phase drug_name
G0    CVT-313             0.264488       -0.081540      -0.368986
      Control             0.368904        0.016761      -0.460750
      Dinaciclib         -1.336910       -0.340488      -1.700270
      PF-3600            -0.406788        1.547176       1.301640
      Palbociclib         1.349624       -1.057431       1.185365
      RO-3306             0.824129       -1.152430      -0.455791
      Samuraciclib       -1.473801        1.390384       0.655070
      Talazoparib         0.410354       -0.322433      -0.156278
G1    CVT-313             0.502547       -0.125997      -0.414630
      Control             0.068703       -0.132529      -0.767085
      Dinaciclib         -1.271571       -0.620290      -1.640784
      PF-3600            -0.609556        1.537700       1.435615
      Palbociclib         0.579567       -1.023882       0.951133
      RO-3306             1.442771       -1.025236      -0.337683
      Samuraciclib       -1.376766        1.453886       0.677163
      Talazoparib         0.664305       -0.063652       0.096271
G2    CVT-313             0.588125        0.190183      -0.338819
      Control             0.329452        0.118360      -0.778901
      Dinaciclib         -1.033746       -0.607989      -1.540542
      PF-3600            -0.584918        1.795267       1.434470
      Palbociclib         0.658821       -0.927038       1.193686
      RO-3306             1.624274       -1.141547      -0.278026
      Samuraciclib       -1.427842        1.004236       0.539993
      Talazoparib        -0.154166       -0.431472      -0.231861
M     CVT-313             0.378030       -0.136762      -0.342891
      Control             0.172643        0.095260      -0.550377
      Dinaciclib         -1.103135       -2.111985      -1.586171
      PF-3600            -0.560309        0.955144       1.729287
      Palbociclib         0.587447        0.050699       0.461676
      RO-3306             1.632012       -0.384860      -0.405286
      Samuraciclib       -1.468631        0.395802       0.823895
      Talazoparib         0.361943        1.136702      -0.130134
S     CVT-313             0.690393        0.340341      -0.228581
      Control             0.050200       -0.340341      -0.925840
      Dinaciclib         -1.075641       -0.148186      -1.529265
      PF-3600            -0.745051        1.166338       1.359433
      Palbociclib         0.681427       -1.030712       1.124742
      RO-3306             1.099848       -1.517230      -0.515139
      Samuraciclib       -1.552441        1.417409       0.600311
      Talazoparib         0.851264        0.112381       0.114339

                    cyto_mean_p16  cyto_mean_PH3  cyto_mean_p65  \
phase drug_name
G0    CVT-313           -0.699605       0.003832      -1.010492
      Control           -0.794282       1.108728      -0.082023
      Dinaciclib        -1.508008      -1.823057      -1.513207
      PF-3600            1.181229       0.502545       0.648606
      Palbociclib        0.523614      -0.118640       0.735519
      RO-3306            0.193807       1.054676      -0.026712
      Samuraciclib      -0.251488      -0.997742       1.609257
      Talazoparib        1.354732       0.269658      -0.360949
G1    CVT-313           -0.602599       0.003358      -1.577701
      Control           -0.697275       0.203302      -0.228622
      Dinaciclib        -1.498346      -1.878750      -1.339773
      PF-3600            1.148621       0.661087       0.487521
      Palbociclib       -0.062067      -0.077839       1.032704
      RO-3306            0.414837       1.143592       0.185823
      Samuraciclib      -0.237444      -0.942950       1.099528
      Talazoparib        1.534272       0.888200       0.340519
G2    CVT-313           -0.612888       0.167989      -0.844903
      Control           -0.775332       0.765804      -0.168211
      Dinaciclib        -1.381978      -1.776441      -1.173441
      PF-3600            1.510023      -0.013145      -0.059449
      Palbociclib       -0.077377       0.017051       0.351253
      RO-3306            0.793540       1.409075       0.184146
      Samuraciclib      -0.452400      -1.020348       2.131424
      Talazoparib        0.996413       0.450015      -0.420819
M     CVT-313           -0.966902      -0.721326      -0.876942
      Control           -0.513587       0.777836      -0.008238
      Dinaciclib        -1.371091      -0.913610      -1.412162
      PF-3600            1.757512      -1.078580       1.932606
      Palbociclib       -0.080309       0.556698       0.562194
      RO-3306            0.208015       1.266254       0.175989
      Samuraciclib       0.085726      -0.932821       0.019398
      Talazoparib        0.880636       1.045549      -0.392845
S     CVT-313           -0.446056       0.375193      -1.231893
      Control           -0.741299       0.253882      -0.445689
      Dinaciclib        -1.490599      -1.761302      -1.454951
      PF-3600            1.330808       0.269320       0.465310
      Palbociclib        0.095497       0.029392       1.463804
      RO-3306            0.298171       0.900938       0.183638
      Samuraciclib      -0.446838      -1.218032       0.866250
      Talazoparib        1.400316       1.150609       0.153531

                    cyto_mean_pAKT  ...  nuclear_mean_bCat  nuclear_mean_SKP2  \
phase drug_name                     ...
G0    CVT-313            -0.240615  ...          -0.802755           0.516096
      Control            -0.860622  ...           0.027453          -0.871205
      Dinaciclib         -0.902097  ...          -1.085738          -1.662634
      PF-3600            -0.013465  ...           1.977592           1.115348
      Palbociclib        -0.037071  ...          -0.613982           1.211224
      RO-3306             2.308701  ...          -0.566815          -0.550680
      Samuraciclib       -0.018947  ...           0.549005          -0.167811
      Talazoparib        -0.235884  ...           0.515240           0.409661
G1    CVT-313            -0.645490  ...          -0.906029          -0.739796
      Control            -0.631363  ...           0.036272          -1.612773
      Dinaciclib         -0.745270  ...          -1.372373           0.271309
      PF-3600             0.088105  ...           1.471314           1.005414
      Palbociclib        -0.151817  ...          -0.431506          -0.502429
      RO-3306             2.314430  ...          -0.483594          -0.301024
      Samuraciclib        0.214162  ...           0.463217           1.513351
      Talazoparib        -0.442756  ...           1.222699           0.365947
G2    CVT-313            -0.242917  ...          -0.983457          -0.450729
      Control            -0.674963  ...          -0.323383          -0.649377
      Dinaciclib         -0.726753  ...          -0.952624          -0.687136
      PF-3600            -0.173262  ...           1.803634           2.386363
      Palbociclib        -0.123195  ...          -0.576852           0.031326
      RO-3306             2.407600  ...          -0.477073          -0.320319
      Samuraciclib       -0.291114  ...           0.938741           0.013153
      Talazoparib        -0.175396  ...           0.571013          -0.323281
M     CVT-313            -0.442129  ...          -0.755453           0.684328
      Control             0.016898  ...          -0.201984          -0.587703
      Dinaciclib         -1.271318  ...          -1.463156          -0.696205
      PF-3600            -0.513429  ...           0.926242           1.515003
      Palbociclib        -0.255095  ...          -0.183104           1.013965
      RO-3306             2.196006  ...          -0.567594          -0.367478
      Samuraciclib        0.152718  ...           0.615607          -0.065617
      Talazoparib         0.116350  ...           1.629441          -1.496294
S     CVT-313            -0.828606  ...          -0.816679          -0.563676
      Control            -1.396421  ...          -0.433668          -1.243162
      Dinaciclib         -1.090555  ...          -0.953181          -0.751453
      PF-3600             0.499209  ...           1.447010           1.970147
      Palbociclib        -0.010745  ...          -0.448425          -0.011860
      RO-3306             1.284977  ...          -0.769945          -0.374372
      Samuraciclib        0.565498  ...           1.433867           0.292693
      Talazoparib         0.976643  ...           0.541020           0.681684

                    nuclear_mean_E2F1  nuclear_mean_HER2  nuclear_mean_YAP1  \
phase drug_name
G0    CVT-313               -1.146526          -1.159544          -1.174268
      Control               -0.993715           0.528351          -1.049086
      Dinaciclib             0.751833          -0.904430          -0.181358
      PF-3600               -0.375325           0.057237           1.947707
      Palbociclib            1.455971          -0.594109           0.114366
      RO-3306               -0.999086          -0.667444          -0.519050
      Samuraciclib           0.753268           1.408411           0.572816
      Talazoparib            0.553579           1.331528           0.288873
G1    CVT-313               -1.200660          -1.524647          -1.050034
      Control               -1.031217          -0.295250          -0.761210
      Dinaciclib             0.631629          -0.451570           0.063444
      PF-3600                1.716513           0.548371           1.134474
      Palbociclib           -0.600087          -0.422821           0.452314
      RO-3306               -0.513200          -0.541109          -1.016714
      Samuraciclib           0.377823           1.311701           1.612366
      Talazoparib            0.619198           1.375324          -0.434641
G2    CVT-313               -1.540845          -1.247437          -1.039390
      Control                1.465546          -0.208149          -0.632336
      Dinaciclib             0.908454           0.311652          -0.274351
      PF-3600                0.534053           1.842067           1.614261
      Palbociclib           -0.804336          -1.111522           0.154205
      RO-3306               -0.402756          -0.475818          -1.176531
      Samuraciclib           0.442187           0.607405           1.183952
      Talazoparib           -0.602303           0.281803           0.170190
M     CVT-313               -0.544798          -0.697317           0.949056
      Control               -0.553838          -0.366754          -1.415543
      Dinaciclib            -0.661150          -1.019131           1.172586
      PF-3600               -0.000473           0.467448           0.117757
      Palbociclib            2.398890           1.887185           1.068174
      RO-3306               -0.010304           0.898831          -0.786410
      Samuraciclib          -0.374001          -0.769501          -0.962731
      Talazoparib           -0.254326          -0.400762          -0.142889
S     CVT-313               -1.341189          -1.469651          -0.326973
      Control               -0.425973          -0.994331           0.591319
      Dinaciclib            -1.471359           0.241983          -0.354336
      PF-3600               -0.019147           0.627291           0.269031
      Palbociclib            1.049172          -0.329342           1.601319
      RO-3306                0.477173          -0.431256          -1.842199
      Samuraciclib           0.748831           0.770711           0.470049
      Talazoparib            0.982493           1.584594          -0.408209

                    nuclear_mean_CDT1  nuclear_mean_pCdc6  nuclear_mean_cycE2  \
phase drug_name
G0    CVT-313               -1.108770           -0.130079           -0.770307
      Control               -1.343590            0.569786            0.183779
      Dinaciclib             1.816337           -1.761892           -1.376302
      PF-3600                0.552047            1.264016            1.333501
      Palbociclib            0.396076            0.541866            1.297248
      RO-3306                0.226367           -1.137410           -0.678666
      Samuraciclib          -0.334297            0.605634            0.533068
      Talazoparib           -0.204171            0.048079           -0.522321
G1    CVT-313               -0.513370           -0.372248           -0.805014
      Control                0.026035            0.206634           -0.318099
      Dinaciclib            -1.452655           -1.874035           -1.556691
      PF-3600               -0.051899            1.317222            1.553837
      Palbociclib           -0.346386            0.740179            0.914610
      RO-3306                2.051881           -0.810594           -0.515214
      Samuraciclib          -0.211533            0.234512            0.516838
      Talazoparib            0.497926            0.558330            0.209732
G2    CVT-313               -1.098638           -0.486319           -0.902778
      Control                0.157892            0.000263           -0.419920
      Dinaciclib            -0.331152           -1.611601           -1.024435
      PF-3600                2.148430            1.227851            1.972497
      Palbociclib           -0.934072            0.489286            0.518071
      RO-3306               -0.245476           -0.715134           -0.405384
      Samuraciclib          -0.027365           -0.260743            0.679337
      Talazoparib            0.330381            1.356398           -0.417388
M     CVT-313                0.519133           -0.705745           -0.248886
      Control               -0.619166            0.009831           -0.648166
      Dinaciclib            -0.658826           -0.777942           -0.637650
      PF-3600                0.339661           -0.684979            2.109411
      Palbociclib           -0.585928            0.519608            0.266116
      RO-3306               -0.028530           -0.500795           -0.644334
      Samuraciclib          -1.051510           -0.073842            0.662161
      Talazoparib            2.085165            2.213864           -0.858653
S     CVT-313               -1.288374           -0.117587           -0.595858
      Control                1.687119           -0.060430           -0.735097
      Dinaciclib            -1.116351           -1.683580           -0.956261
      PF-3600                0.608840            1.187067            2.067229
      Palbociclib           -0.517231            1.070314            0.647374
      RO-3306               -0.253923           -1.040456           -0.477880
      Samuraciclib           0.159193           -0.066914            0.391292
      Talazoparib            0.720728            0.711586           -0.340800

                     DNA_int    pRB/RB
phase drug_name
G0    CVT-313      -0.898449 -0.353561
      Control      -0.962152 -0.353554
      Dinaciclib   -0.368658 -0.353559
      PF-3600       0.581046 -0.353542
      Palbociclib  -0.878167 -0.353558
      RO-3306      -0.277070  2.474874
      Samuraciclib  1.312503 -0.353544
      Talazoparib   1.490946 -0.353557
G1    CVT-313      -0.736172 -0.353555
      Control      -0.766089 -0.353551
      Dinaciclib   -0.787928  2.474874
      PF-3600       0.617925 -0.353559
      Palbociclib  -0.947186 -0.353555
      RO-3306       0.069512 -0.353546
      Samuraciclib  0.676886 -0.353555
      Talazoparib   1.873053 -0.353552
G2    CVT-313      -0.515361 -0.833108
      Control      -0.948870 -0.517887
      Dinaciclib   -0.329687 -0.134693
      PF-3600       1.774955 -0.279161
      Palbociclib  -1.230300 -0.316781
      RO-3306       0.535310  1.905847
      Samuraciclib  0.866795 -0.959390
      Talazoparib  -0.152841  1.135173
M     CVT-313       0.382815 -0.271255
      Control       0.248830 -0.207825
      Dinaciclib    0.789592  0.690309
      PF-3600      -1.695733 -1.118926
      Palbociclib  -1.358979 -0.777278
      RO-3306       0.276579  1.858329
      Samuraciclib  1.152087 -0.822250
      Talazoparib   0.204809  0.648895
S     CVT-313      -0.467310 -0.353558
      Control      -0.987689 -0.353556
      Dinaciclib   -0.278094 -0.353553
      PF-3600       0.774575 -0.353555
      Palbociclib  -0.578774 -0.353553
      RO-3306      -0.606968  2.474874
      Samuraciclib  0.040997 -0.353560
      Talazoparib   2.103264 -0.353539

[40 rows x 103 columns]

In [148]:
phases = pseudobulk_norm_df.index.get_level_values('phase').unique()
drugs = pseudobulk_norm_df.index.get_level_values('drug_name').unique()

np_tensor = np.stack(
    [pseudobulk_norm_df.xs(ph, level='phase').loc[drugs].values for ph in phases],
    axis=2
)

np_tensor.shape

(8, 103, 5)

### 2.2 Tucker decomposition:

In [153]:
tensor = tl.tensor(np_tensor)
core, factors = tucker(tensor, rank=[3, 10, 3])

In [154]:
factors[1]

array([[ 0.12537189,  0.11386294,  0.00539591, ...,  0.1119039 ,
        -0.06618373, -0.0473939 ],
       [ 0.03189943,  0.19689368, -0.00333134, ...,  0.0595155 ,
         0.07132969,  0.01628402],
       [ 0.16489949,  0.03556387, -0.0239627 , ...,  0.0108595 ,
        -0.0460032 ,  0.0537256 ],
       ...,
       [ 0.13792678, -0.1051307 , -0.06432658, ..., -0.04611838,
        -0.00616503,  0.00756898],
       [ 0.04532917, -0.04074751,  0.16966285, ...,  0.17305517,
        -0.14366353, -0.0056121 ],
       [-0.02987516,  0.08289876,  0.06351717, ...,  0.09454679,
         0.19655175, -0.02441366]], shape=(103, 10))

---